[theme]
base = "light"
primaryColor = "#2563EB"
backgroundColor = "#F8FAFC"
secondaryBackgroundColor = "#E5E7EB"
textColor = "#111827"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
